module Day07Test exposing (suite)

import Day07 exposing (..)
import Expect
import Test exposing (Test, test)


input : String
input =
    String.trim """
.......S.......
...............
.......^.......
...............
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
...............
"""


parserTestInput : String
parserTestInput =
    String.trim """
.......S.......
.......|.......
......|^|......
......|.|......
.....|^|^|.....
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
...............
"""


suite : Test
suite =
    Test.concat
        [ test "parse" <|
            \_ ->
                Expect.equal (parse parserTestInput)
                    [ [ Empty, Empty, Empty, Empty, Empty, Empty, Empty, Start, Empty, Empty, Empty, Empty, Empty, Empty, Empty ]
                    , [ Empty, Empty, Empty, Empty, Empty, Empty, Empty, Beam, Empty, Empty, Empty, Empty, Empty, Empty, Empty ]
                    , [ Empty, Empty, Empty, Empty, Empty, Empty, Beam, Splitter, Beam, Empty, Empty, Empty, Empty, Empty, Empty ]
                    , [ Empty, Empty, Empty, Empty, Empty, Empty, Beam, Empty, Beam, Empty, Empty, Empty, Empty, Empty, Empty ]
                    , [ Empty, Empty, Empty, Empty, Empty, Beam, Splitter, Beam, Splitter, Beam, Empty, Empty, Empty, Empty, Empty ]
                    , [ Empty, Empty, Empty, Empty, Empty, Empty, Empty, Empty, Empty, Empty, Empty, Empty, Empty, Empty, Empty ]
                    , [ Empty, Empty, Empty, Empty, Empty, Splitter, Empty, Splitter, Empty, Splitter, Empty, Empty, Empty, Empty, Empty ]
                    , [ Empty, Empty, Empty, Empty, Empty, Empty, Empty, Empty, Empty, Empty, Empty, Empty, Empty, Empty, Empty ]
                    , [ Empty, Empty, Empty, Empty, Splitter, Empty, Splitter, Empty, Empty, Empty, Splitter, Empty, Empty, Empty, Empty ]
                    , [ Empty, Empty, Empty, Empty, Empty, Empty, Empty, Empty, Empty, Empty, Empty, Empty, Empty, Empty, Empty ]
                    , [ Empty, Empty, Empty, Splitter, Empty, Splitter, Empty, Empty, Empty, Splitter, Empty, Splitter, Empty, Empty, Empty ]
                    , [ Empty, Empty, Empty, Empty, Empty, Empty, Empty, Empty, Empty, Empty, Empty, Empty, Empty, Empty, Empty ]
                    , [ Empty, Empty, Splitter, Empty, Empty, Empty, Splitter, Empty, Empty, Empty, Empty, Empty, Splitter, Empty, Empty ]
                    , [ Empty, Empty, Empty, Empty, Empty, Empty, Empty, Empty, Empty, Empty, Empty, Empty, Empty, Empty, Empty ]
                    , [ Empty, Splitter, Empty, Splitter, Empty, Splitter, Empty, Splitter, Empty, Splitter, Empty, Empty, Empty, Splitter, Empty ]
                    , [ Empty, Empty, Empty, Empty, Empty, Empty, Empty, Empty, Empty, Empty, Empty, Empty, Empty, Empty, Empty ]
                    ]

        -- , test "solve" <|
        --     \_ ->
        --         Expect.equal (solve (parse input)) (Debug.todo "")
        ]
